### ISSUE TITLE
Clarifications of hotkey.modal.new within applications.lua

### ISSUE THREAD

**Issue by peterpme** [asmagill/hammerspoon-config#1]
Hello,

I'd like to start by saying thank you for open-sourcing your config. It's allowed me to see how powerful Hammerspoon can be!

I was hoping you could clarify how I could extract this into my own config:

```lua
    fnutils.each({
        { key = "a", app = "Arduino" },
        { key = "p", app = "Activity Monitor" },
        { key = "t", app = "Terminal" },
        { key = "e", app = "TextWrangler" },
        { key = "f", app = "Finder" },
        { key = "m", app = "Mail" },
        { key = "s", app = "Safari" },
        { key = "c", app = "Console" },
    },
        function(object)
            app:bind(mods.casc, object.key,
                function() application.launchOrFocus(object.app) end,
                function() app:exit() end
            )
        end
    )
```

This is within:
[utils/_key/applications.lua](https://github.com/asmagill/hammerspoon-config/blob/07adccec1ba6b773fccddbaefb5321c5733ed310/utils/_keys/applications.lua)

Maybe I'm missing something but I noticed that `hotkey.modal.new(mods.CAsC)` could be an internal mod dependency. Do I have to bring all of that over as well from your config? I see a few comments mentioning extracting out if it becomes useful.

Also, what exactly does `mods.casc` mean when binding in this context?

Any help would be greatly appreciated!

Thanks again,
Peter

**Comment by asmagill** [comment]
The `mods.[cC][aA][sS][cC]` are defined in a third-party module named `hs._asm.extras`... it's a place I put things that don't quite fit anywhere else and that I don't really expect will be made part of the core Hammerspoon modules.  The relevant portion to you here, modified slightly to be stand-alone, is:

``` lua
local mods = {
    casc = {                     }, casC = {                       "ctrl"},
    caSc = {              "shift"}, caSC = {              "shift", "ctrl"},
    cAsc = {       "alt"         }, cAsC = {       "alt",          "ctrl"},
    cASc = {       "alt", "shift"}, cASC = {       "alt", "shift", "ctrl"},
    Casc = {"cmd"                }, CasC = {"cmd",                 "ctrl"},
    CaSc = {"cmd",        "shift"}, CaSC = {"cmd",        "shift", "ctrl"},
    CAsc = {"cmd", "alt"         }, CAsC = {"cmd", "alt",          "ctrl"},
    CASc = {"cmd", "alt", "shift"}, CASC = {"cmd", "alt", "shift", "ctrl"},
}
```

It's basically a short hand that for me makes it obvious which modifiers I have in mind... the letters  stand for Command-Alt-Shit-Control, and if the letter is uppercase, then it means the modifier is expected and if its lowercase, then it isn't... so `mods.CAsc` would mean `{ "cmd", "alt" }`.

Since the letters corresponding to the application name in the snippit you posted are part of a modal dialog, the `mods.casc` is basically an empty table meaning that no modifiers are expected.

Since I created the table, people have added additional code to `hs.hotkey` that allows you to use the Unicode character representing the modifiers (e.g. a combination of one or more of "⌘⌥⇧⌃") and use a string rather than a table to specify the modifiers... but this made sense to me, so I still use it.

With modal hotkeys, the internally bound ones are only valid if the parent hotkey is first invoked... so under normal circumstances, "a", "p", "t", etc. are all regular characters doing whatever (usually entering text)... but when I tap "Cmd-Alt-Control A", then "a", "p", "t", etc temporarily become launchers for the specified application.  The `app:exit()` line at the end of each individually bound key makes sure that as soon as the application is launched, we exit the modal mode and the letters go back to being just letters with no bindings again.

**Comment by peterpme** [comment]
This makes a lot of sense, thank you! I'll close this issue for now!
