### ISSUE TITLE
viKeys not working

### ISSUE THREAD

**Issue by diegodesouza** [asmagill/hammerspoon-config#3]
So i've been trying to get the fn + hjkl keys to work as in vi mode. But it's been a hassle. I copied your `viKeys.lua` into my `init.lua` and it hasn't worked, am I missing something?

**Comment by asmagill** [comment]
Key related eventtaps do require accessibility to be enabled for Hammerspoon... you can check Hammerspoon's preferences or type `hs.accessibilityState(true)` in the Hammerspoon console to check... that's the first thing I'd look at.

The other possibility that comes to mind is that the file as it stands is expected to be a separate file which is loaded by your `init.lua` file into a global variable  (e.g. `viKeys = require("utils._keys.viKeys")` in the case of my folder layout)... if you just copied the contents into your `init.lua` file, you'll need to change the `local module = {}` line to `module = {}`.  The simplest explanation is that local variables only remain in scope until the end of the current context, in this case, the `init.lua` file.  As soon as its execution completes, a local variable which has not been also stored in a global variable is eligible for garbage collection.  When this happens, any watchers or eventtaps or timers assigned in that local variables space (i.e. the ones I store in `module` in the file) get stopped so that they can be collected as well.

If neither of these help, can you post your `init.lua` (or whatever file you put the viKeys code into) file somewhere I can review?  As a comment here, or in a gist or repository somewhere?

**Comment by jakejx** [comment]
Not the OP, but I can't seem to get vikeys to work too. Here is my init.lua:

```
module = {}

module.debugging = true -- whether to print status updates

local eventtap = require "hs.eventtap"
local event    = eventtap.event
local inspect  = require "hs.inspect"

local keyHandler = function(e)
    local watchFor = { i = "left", j = "down", k = "up", l = "right" }
    local actualKey = e:getCharacters(true)
    local replacement = watchFor[actualKey:lower()]
    if replacement then
        local isDown = e:getType() == event.types.keyDown
        local flags  = {}
        for k, v in pairs(e:getFlags()) do
            if v and k ~= "ctrl" then -- ctrl will be down because that's our "wrapper", so ignore it
                table.insert(flags, k)
            end
        end
        if module.debugging then print("viKeys: " .. replacement, inspect(flags), isDown) end
        local replacementEvent = event.newKeyEvent(flags, replacement, isDown)
        if isDown then
            -- allow for auto-repeat
            replacementEvent:setProperty(event.properties.keyboardEventAutorepeat, e:getProperty(event.properties.keyboardEventAutorepeat))
        end
        return true, { replacementEvent }
    else
        return false -- do nothing to the event, just pass it along
    end
end

local modifierHandler = function(e)
    local flags = e:getFlags()
    local onlyControlPressed = false
    for k, v in pairs(flags) do
        onlyControlPressed = v and k == "ctrl"
        if not onlyControlPressed then break end
    end
    -- you must tap and hold ctrl by itself to turn this on
    if onlyControlPressed and not module.keyListener then
        if module.debugging then print("viKeys: keyhandler on") end
        module.keyListener = eventtap.new({ event.types.keyDown, event.types.keyUp }, keyHandler):start()
    -- however, adding additional modifiers afterwards is ok... its only when ctrl isn't down that we switch back off
    elseif not flags.ctrl and module.keyListener then
        if module.debugging then print("viKeys: keyhandler off") end
        module.keyListener:stop()
        module.keyListener = nil
    end
    return false
end

module.modifierListener = eventtap.new({ event.types.flagsChanged }, modifierHandler)

module.start = function()
    module.modifierListener:start()
end

module.stop = function()
    if module.keyListener then
        module.keyListener:stop()
        module.keyListener = nil
    end
    module.modifierListener:stop()
end

module.start() -- autostart

return module
```

Thanks for the help!

**Comment by asmagill** [comment]
I'm assuming that the changes to make it use the `ctrl` modifier instead of the `fn` modifier and the use of `i` instead of `h` are changes you made yourself? (I may - can't recall - have used `ctrl` in an early version of mine, but I don't recall using the `i` key by mistake in one of my earlier versions of this, which is why I ask)

When I replace my code with this, it works for me (with `ctrl` and `i`, `j`, `k`, and `l`), so I have to ask if you tried checking the Accessibility setting for Hammerspoon?  (what does `hs.accessibilityState(true)` return when typed into the Hammerspoon console?)

The other thing that caught my attention is you identified the above file as your `init.lua` file?  Usually I put things like this into separate files and then include them from `init.lua` with something like `viKeys = require("otherfilename"), but I can't imagine why that would make a difference since you do make `module` global and if I recall correctly, Hammerspoon ignores the return value of `init.lua`... but I just wanted to make sure because I can swap out my config and try it that way later today (it's after midnight here and I was just about to shutdown for the "night") and see if it makes a difference, though I don't think it should.

And just to make sure, what version of Hammerspoon are you running?  (type `hs.processInfo.version` into the Hammerspoon console)
